"""
Models initialization.
"""

from .enums import (
    AuthTypeEnum,
    ProjectPriorityEnum,
    ProjectStatusEnum,
    TaskDomainEnum,
    TaskPriorityEnum,
    TaskStatusEnum,
    TaskTypeEnum,
)
from .database import Base, Note, Project, Task, User
from .misc import Root200Response, Health200Response
from .auth import (
    RegisterParams,
    Register201Response,
    SessionData,
    UserCreds,
    LoginParams,
    Login200Response,
    RefreshParams,
    Refresh200Response,
    Logout200Response,
)
from .note import (
    CreateNoteParams,
    CreateNote201Response,
    DeleteNote200Response,
    GetAllNotesParams,
    GetAllNotes200Response,
    GetNote200Response,
    ToggleNotePin200Response,
    UpdateNote200Response,
    UpdateNoteParams,
    NoteResponse,
)
from .project import (
    CreateProjectParams,
    CreateProject201Response,
    GetAllProjectsParams,
    GetAllProjects200Response,
    GetRecentProjects200Response,
    RecentProjectItem,
    GetProject200Response,
    ToggleProjectFavorite200Response,
    ToggleProjectArchived200Response,
    UpdateProjectParams,
    UpdateProject200Response,
    DeleteProject200Response,
)
from .user import (
    GetUser200Response,
    UpdateUserParams,
    UpdateUser200Response,
    UpdateUserPasswordParams,
    UpdateUserPassword200Response,
)


__all__ = [
    "AuthTypeEnum",
    "ProjectStatusEnum",
    "ProjectPriorityEnum",
    "TaskStatusEnum",
    "TaskTypeEnum",
    "TaskPriorityEnum",
    "TaskDomainEnum",
    "Base",
    "Health200Response",
    "Note",
    "Project",
    "Task",
    "Root200Response",
    "User",
    "RegisterParams",
    "Register201Response",
    "SessionData",
    "UserCreds",
    "LoginParams",
    "Login200Response",
    "RefreshParams",
    "Refresh200Response",
    "CreateNoteParams",
    "CreateNote201Response",
    "DeleteNote200Response",
    "GetAllNotesParams",
    "GetAllNotes200Response",
    "GetNote200Response",
    "ToggleNotePin200Response",
    "UpdateNoteParams",
    "UpdateNote200Response",
    "NoteResponse",
    "CreateProjectParams",
    "CreateProject201Response",
    "Logout200Response",
    "GetAllProjectsParams",
    "GetAllProjects200Response",
    "GetRecentProjects200Response",
    "RecentProjectItem",
    "GetProject200Response",
    "GetUser200Response",
    "UpdateUserParams",
    "UpdateUser200Response",
    "UpdateUserPasswordParams",
    "UpdateUserPassword200Response",
    "ToggleProjectFavorite200Response",
    "ToggleProjectArchived200Response",
    "UpdateProjectParams",
    "UpdateProject200Response",
    "DeleteProject200Response",
]
